package uk.co.planetcom.infrastructure.ota.server.enums;

public enum AssetType {
    ASTRO_ANDROID_FW,
    ASTRO_ANDROID_FW_PATCH,
    ASTRO_BOOTLOADER,
    CODI_BOOTLOADER,
    CODI_CODID,
    CODI_FIRMWARE,
    CODI_RESOURCES,
    COSMO_ANDROID_FW,
    COSMO_ANDROID_FW_PATCH,
    COSMO_BOOTLOADER,
    GEMINI_ANDROID_FW,
    GEMINI_ANDROID_FW_PATCH,
    GEMINI_BOOTLOADER
}
